import React, { Component } from 'react';

class TermsComp extends Component {
    render() {
        return (
            <div className="mainterms">
                <h1 className="maint">Terms and Conditions</h1>
                <p>MOST SEARCHED FOR ON FLIPKART:iPhone 13iPhone 13 ProiPhone 13 Pro MaxiPhone 13 MiniTV & Appliances Big Billion Days SaleFlipkart Pay Later EMIBig Billion DaysFlipkart Motor Vehicle InsuranceFlipkart QuickEd A Mamma ClothingBooksFlipkart Electronics: TV & Home Appliances SaleGrand Kitchen & Home Appliances SaleAuto Accessories StoreStreak SunglassesGold CoinsBGM Big Billion Day SaleHome BBD Dhamaka SaleFlipkart PlusFlipkart Super CoinFlipkart COVID-19 InsuranceFlipkart Help CentreFlipkart Track OrdersFlipkart Manage OrdersFlipkart Return OrdersFlipkart Gift Cards StoreSareesFlipkart Axis Bank Credit CardFlipkart Pay LaterJewelleryWatchesGold CoinMangalsutraSunglassesMi SunglassesBackpacksRay Ban Sunglasses</p>
                <p>MOBILES:iPhone 12 64GBiPhone 12 Pro 512GBiPhone 12 128GBVivo Y91iVivo Y11Vivo Y15Vivo Y50Vivo Y12Reno2 FOppo A12Oppo F15Oppo A31Samsung A71Samsung A51Samsung A31Realme X2Realme 5Infinix Hot 8iPhone 11iPhone 11 ProiPhone 11 Pro MaxMobile Offersiphone xiphone 8iphone 7iphone 6Redmi 5A4G MobileNokia MobileSamsung MobileiphoneOppo MobileVivo Mobile                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </p>
                <p>CAMERA:GoPro Action CameraNikon CameraCanon CameraSony CameraCanon DSLRNikon DSLR                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                <p>LAPTOPS:Microsoft Surface Go Pentium Gold 64GBMicrosoft Surface Go Pentium 128GBBranded LaptopsApple LaptopsAcer LaptopsLenovo LaptopsDell LaptopsAsus LaptopsHP LaptopsGaming Laptops2 in 1 LaptopsBusiness Laptops                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </p>
                <p>TVS:TVs Big Billion Days SaleMotorola TVRedmi Smart TelevisionsOnePlus TVsRealme SLED 4K Smart TVsMI 43 Inch 4K TVMI 40 Inch TVMi 65 Inch TVSamsung 32 Smart TVLG TVTVSony TVSamsung TVMi 49 Inch Smart TVAndroid TelevisionIffalcon TvMi TV                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </p>
                <p>LARGE APPLIANCES:Large Appliances Big Billion Days SaleWashing MachinesRefrigeratorsAir ConditionersAir FryersAppliance Parts and AccessoriesBread MakersCake MakersCoffee MakersCotton Candy MakersCupcake MakersDonut MakersDough PressesEgg CookersElectric CookersElectric Deep FryersElectric Jug(Heater) / Travel KettlesElectric TandoorsElectric Cooking HeatersElectric PansFlour MillsFood MakersFood ProcessorsHand BlendersIce Cream MakersIndian Coffee FiltersInduction CooktopsInverter BatteriesInverter BatteriesInverters / stabilizerIrons / Iron BoxLandline PhonesMixer Grinder JuicerNoodles Spaghetti MakerPizza MakersPizzelle MakersPop Up ToastersPopcorn MakersPotato Twister MachineRoti MakersSandwich MakersSlow CookersSoda MakersVada MakersVoltage StabilizersWaffle MakersWet GrindersAir PurifiersChimneysMicrowave OvensOven Toaster GrillSewing MachinesVacuum CleanersWater PurifierAir CoolersFanImmersion RodsRoom HeatersWater Heater GeysersVoltas ACHitachi ACLloyd ACBlue Star ACDaikin ACLG ACSamsung RefrigeratorsHaier RefrigeratorWhirlpool Refrigerator </p>
                <p>CLOTHING:Men ShirtsKurta PajamaKurtasMen T-ShirtsJeansCrop TopsRaincoatMen SuitsMen TrousersMens BlazersSareeDressesBaby girl dressesFloral DressesSkirtsKids DressesDesigner Salwar SuitsBraDesigner KurtisTrack PantMen KurtasGym WearParty DressesPalazzo SuitsBoys ClothingGlovesNightyMaxi DressesAnarkaliIndo Western DressGownsCulottesSherwaniGirls ClothesSalwar SuitsTopsLehengaDress MaterialsIndo western for menKurtisDesigner SareesSummer DressesLeggingsDesigner BlousesBlouse DesignsBanarasi SareesSilk SareesTissue SareesCotton SareesShortsBlouseLong SkirtsPalazzoWinter JacketsJoggersMini DressesNight SuitsBanarsi SuitInnerwearSports WearCapChanderi SareesLinen SareesPaithani SareesOff the shoulder topsPantiesGirls ShortsShrugsSalwarGirls DressesBikiniPajamasKids WearManyavar KurtasWomens TrousersJacketsWestern WearLevis JacketsSleepwearShawlsCardigansPulloverStolesDenim JacketsFrocksClothingKids ClothingWinter WearScarvesSports JacketsGeorgette SareesEthnic WearBriefs & TrunksSweatshirts                                                                </p>
                <p>FOOTWEAR:ShoesAdidas ShoesReebok ShoesNike ShoesPuma ShoesBootsBata ShoesWoodland ShoesSkechers ShoesSneakersWomens BootsSports ShoesLoafersSandalsLotto Sports ShoesCasual ShoesWomens Skechers ShoesAsics Sports ShoesFormal ShoesSchool Shoes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </p>
                <p>GROCERIES:PhonePe Grocery VoucherHand WashSugar Jaggery SaltsRiceMasala & SpicesDal PulsesAttaCookiesNoodlesGheeDry FruitsToor DalOlive OilSoapCashew NutsSunflower OilEggsToilet CleanerHarpic Toilet CleanerDettol SoapMustard OilBiscuitsCheesePatanjali AttaFortune OilAashirvaad AttaButterAmul MilkJuicesTata TeaGrocery StoreGrocery Essential StoreMuesliBreakfast CerealHand WashHand SanitizerLizol Floor CleanerDetergentsChipsTeaMilkChocolatesSoft DrinksRavaCoffeeSona Masoori RiceSugarColgate ToothpasteShampooAlmondsMoong DalInstant CoffeeParle Namkeen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </p>
                <p>BEST SELLING ON FLIPKART:Samsung Galaxy Tab S7+BooksToy StoreCandlesHelmetsWall ClocksBaby FoodChocolatesCyclesCalculatorsLipsticksFastrack WatchesWalletsEarringsGold CoinsHandbags                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </p>
                <p>FURNITURE:Grand Furniture SaleFurnitureSofasBedsDining setsWardrobesMattressesTV UnitsTablesChairsShelvesBean BagsOffice ChairsComputer TableOffice TablesRed SofaWakefit BedsWhite SofaWakefit MattressGreen SofaBlack SofaBrown Sofa                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </p>
            </div >
        );
    }
}

export default TermsComp;